from django.core.exceptions import ValidationError


def validate_dishes(value):
    a = 5
